### PR TITLE
Add black box integration tests via Docker

### PR DESCRIPTION
**Pull request by rob-mccann**
This spawns up the example koa app and tries to retrieve the PDF from it.

Has the effect of testing the example app and also the integration with Koa and PDFMake.

### CODE REVIEW

**Comment by mtlewis** [comment]
I'm wondering whether we should consider simplifying this example app before covering it with tests.  It kinda feels like it would be simpler to have an example app that just saves the PDF to a file on startup.

**Comment by rob-mccann** [comment]
@mtlewis I don't have a strong preference. As far as I can see it, this is nice as it tests a closer to real world scenario for us but I can certainly see the advantage in keeping things simple. I'll PR the suggestion too so we can compare.

**Comment by mtlewis** [comment]
Yeah, it’s definitely nice for us that it’s similar to our internal use case, but I worry that it might trick people into thinking the extra scaffolding is somehow required to use the library.

**Comment by rob-mccann** [comment]
Closing in favour of #12

**Pull request closed without merging**
